northbridge:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: parse_only
      user: parse_only
      password: parse_only
      role: NORTHBRIDGE_DBT_CI
      database: NORTHBRIDGE_CI_BASE
      schema: DBT_CI
      warehouse: NORTHBRIDGE_CI_WH
      threads: 1
