name: northbridge
version: '1.0.0'
config-version: 2
profile: northbridge
require-dbt-version: ['>=1.12.2', '<1.13.0']
model-paths: ['models']
test-paths: ['tests']
on-run-start:
  - 'use secondary roles none'
flags:
  send_anonymous_usage_stats: false
vars:
  price_delivery_id: '0a35a13d137e4627ace8d7a9d668f3ce'
  delivery_id: '18ae80085f1043789b5d604ee44dc216'
  business_date: '2025-01-06'
models:
  northbridge:
    +materialized: view
    marts:
      +materialized: table
