name: northbridge
version: '1.0'
config-version: 2
profile: northbridge

model-paths: ['models']
test-paths: ['tests']

on-run-start:
  - 'use secondary roles none'

models:
  northbridge:
    staging:
      +materialized: view
    marts:
      +materialized: table
