northbridge:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gxmgyta-fq45953
      user: NORTHBRIDGE_DBT
      role: NORTHBRIDGE_DBT_DEV
      warehouse: COMPUTE_WH
      database: NORTHBRIDGE_DEV
      schema: DBT_DEV
      threads: 1
      private_key_path: "{{ env_var('NORTHBRIDGE_DBT_KEY_PATH') }}"
      query_tag: northbridge_positions_dev
