-- One-time reset, run through scripts/snow_admin.py as SYSADMIN.
-- Do not rerun after building new dbt models in DBT_DEV.
-- Keep NORTHBRIDGE_DEV.RAW: the new daily pipeline uses that schema.

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- See what is there before deleting it. Save this result if you want a record.
SELECT table_schema, table_name, table_type, row_count
FROM NORTHBRIDGE_DEV.INFORMATION_SCHEMA.TABLES
WHERE table_schema IN ('RAW', 'DBT_DEV', 'OPERATIONS')
ORDER BY table_schema, table_name;

-- These two schemas belong to the previous dbt and close pilots.
DROP SCHEMA IF EXISTS NORTHBRIDGE_DEV.DBT_DEV CASCADE;
DROP SCHEMA IF EXISTS NORTHBRIDGE_DEV.OPERATIONS CASCADE;

-- Stop the old pipes before removing their source tables and stages.
DROP PIPE IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS_PIPE;
DROP PIPE IF EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_PIPE;

-- Old RAW tables. The new DAILY_* tables are deliberately absent.
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.EXECUTIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.ALLOCATIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.CLOSING_PRICES;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.REPLAY_INPUTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTION_REVIEWS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.BROKER_POSITIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.FX_RATES;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.TREASURY_RATES;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.FUND_ADMIN_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.BANK_CASH_STATEMENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING;

-- Old upload locations and file formats are no longer used either.
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_SAMPLE_20250106;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.MARKET_SAMPLE_20250106_08;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.FX_RATES_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.TREASURY_RATES_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.FUND_ADMIN_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.BANK_CASH_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_STAGE;
DROP STAGE IF EXISTS NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING_STAGE;

DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_CSV;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.MARKET_CSV;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES_CSV;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.OMS_JSON;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_JSON;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS_JSON;
DROP FILE FORMAT IF EXISTS NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;

-- Expected result: no DBT_DEV or OPERATIONS schema, and only DAILY_* RAW
-- tables if the new setup has already been run.
SELECT table_schema, table_name, table_type, row_count
FROM NORTHBRIDGE_DEV.INFORMATION_SCHEMA.TABLES
WHERE table_schema IN ('RAW', 'DBT_DEV', 'OPERATIONS')
ORDER BY table_schema, table_name;
