-- Run after 01_daily_raw.sql. The service user is created in 03_loader_user.sql.
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS NORTHBRIDGE_INGEST_DEV;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.RAW TO ROLE NORTHBRIDGE_INGEST_DEV;

GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.DAILY_LANDING
    TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT USAGE ON FILE FORMAT NORTHBRIDGE_DEV.RAW.DAILY_JSON
    TO ROLE NORTHBRIDGE_INGEST_DEV;

GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_OMS_EVENTS
    TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_SETTLEMENT_EVENTS
    TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT SELECT, INSERT, UPDATE ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_DELIVERIES
    TO ROLE NORTHBRIDGE_INGEST_DEV;

GRANT OPERATE, MONITOR ON PIPE NORTHBRIDGE_DEV.RAW.DAILY_OMS_PIPE
    TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT OPERATE, MONITOR ON PIPE NORTHBRIDGE_DEV.RAW.DAILY_SETTLEMENT_PIPE
    TO ROLE NORTHBRIDGE_INGEST_DEV;
