-- One-time setup. Run after 01_daily_raw.sql and 02_ingest_access.sql.
-- This is a public key. The matching private key stays in .secrets/.
USE ROLE SECURITYADMIN;

CREATE USER NORTHBRIDGE_LOADER
    TYPE = SERVICE
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuqj+QvOu78duZ0tU4fFPNzdoZrbATTUWnIM9IVY+8Ou4k0vXuH6djeLRHAppik1zbRGxvRHiIAtB5c+sgoQd2JxhOwhEU8wo8HzWNuSWKTRNLIh4Y6PLqiR/NH/pCSNWULV8ubk9yqvVCrF5IPqHYiAelV3g5TCtph0+O/YiO9gZJeqztxwD4SwIBlr/pU8jZGMBGeS30qYgO6JQk9nlM6D1VreWG43LkNCtm1GJbnw7Y2rSi64IlsjvMf1KksxK6gWFQcDJyg5kCUkxAvdpRwucYTgEBPn+iIJLM3MIG4BsFKDP/LobIXfKeIx6ZU1rWUX34xlOCKXQVie6Nj+eowIDAQAB'
    DEFAULT_ROLE = NORTHBRIDGE_INGEST_DEV
    DEFAULT_WAREHOUSE = COMPUTE_WH
    DEFAULT_NAMESPACE = NORTHBRIDGE_DEV.RAW;

GRANT ROLE NORTHBRIDGE_INGEST_DEV TO USER NORTHBRIDGE_LOADER;
DESCRIBE USER NORTHBRIDGE_LOADER;
