-- File holding area for this one learning delivery. Live execution UNVERIFIED.
USE ROLE SYSADMIN;

CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = FALSE
    NULL_IF = ()
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_SAMPLE_20250106
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.OMS_CSV;

-- Upload only the two prepared CSVs to this stage, without a subfolder.
LIST @NORTHBRIDGE_DEV.RAW.OMS_SAMPLE_20250106;
