-- Run manually in Snowsight. Live execution UNVERIFIED.
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS NORTHBRIDGE_DBT_DEV;
GRANT ROLE NORTHBRIDGE_DBT_DEV TO ROLE SYSADMIN;
SET dbt_developer = CURRENT_USER();
GRANT ROLE NORTHBRIDGE_DBT_DEV TO USER IDENTIFIER($dbt_developer);

USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS NORTHBRIDGE_DEV.DBT_DEV;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.RAW TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.EXECUTIONS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.ALLOCATIONS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.DBT_DEV TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NORTHBRIDGE_DEV.DBT_DEV TO ROLE NORTHBRIDGE_DBT_DEV;

USE ROLE NORTHBRIDGE_DBT_DEV;
SELECT CURRENT_USER() AS login_name, CURRENT_ROLE() AS active_role;
