-- dbt reads RAW and creates models only in DBT_DEV.
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS NORTHBRIDGE_DBT_DEV;

USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS NORTHBRIDGE_DEV.DBT_DEV;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.RAW TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_OMS_EVENTS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_PRICE_EVENTS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_DELIVERIES TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.DBT_DEV TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NORTHBRIDGE_DEV.DBT_DEV TO ROLE NORTHBRIDGE_DBT_DEV;

CREATE USER IF NOT EXISTS NORTHBRIDGE_DBT
    TYPE = SERVICE
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmKdByP2hB4psipSNIZZrbUch0cCZRqWd1hs7AljTnrzG2MMRl3WvglPXmMvlI9E02Xw/jgSDeJftvKK4jXbGHzim3dZ4D71Wjh5ejgOKgASoa+XOexe2hyV44BbV4+rzq2mBEjODrTOugv2ELXOqc5YKI6Mftj+o1YoduLia4VdPXTGssy81vhN64C6wglJnfXfWJol+9z7fmj6V1P4iw84+dUdcqXd7eJPDqoXKB7z0cUpQmpTOhAABPOFzqHRDC1ukCHyPZiXYWfhwlKRCJAAjsvKa9psjmBtewALmLr6YALv5G7Q4L30Mm8OWQ0UntBsWluRouny3pVNmUCcLQIDAQAB'
    DEFAULT_ROLE = NORTHBRIDGE_DBT_DEV
    DEFAULT_WAREHOUSE = COMPUTE_WH
    DEFAULT_NAMESPACE = NORTHBRIDGE_DEV.DBT_DEV;
GRANT ROLE NORTHBRIDGE_DBT_DEV TO USER NORTHBRIDGE_DBT;
