-- Keep opening bank and fund-admin records in RAW with their source paths.
USE ROLE SYSADMIN;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.DAILY_OPENING_EVENTS (
    payload VARIANT,
    source_file VARCHAR,
    source_row_number NUMBER,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

USE ROLE SECURITYADMIN;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_OPENING_EVENTS
    TO ROLE NORTHBRIDGE_INGEST_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_OPENING_EVENTS
    TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DAILY_SETTLEMENT_EVENTS
    TO ROLE NORTHBRIDGE_DBT_DEV;
