-- Prepare the raw prices table and a stage for our saved market snapshot.
-- Live execution UNVERIFIED. This script does not load any records.
USE ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.CLOSING_PRICES (
    valuation_date VARCHAR,
    instrument VARCHAR,
    currency VARCHAR,
    close_price VARCHAR,
    price_basis VARCHAR NOT NULL,
    source_system VARCHAR NOT NULL,
    delivery_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.MARKET_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = FALSE
    NULL_IF = ()
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.MARKET_SAMPLE_20250106_08
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.MARKET_CSV;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.CLOSING_PRICES
    TO ROLE NORTHBRIDGE_DBT_DEV;

USE ROLE SYSADMIN;
DESCRIBE TABLE NORTHBRIDGE_DEV.RAW.CLOSING_PRICES;
