-- Run manually in Snowsight. Prepares storage; does not load records.
USE ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.EXECUTION_TERMS (
    business_date VARCHAR,
    execution_id VARCHAR,
    currency VARCHAR,
    execution_price VARCHAR,
    settlement_due VARCHAR,
    source_system VARCHAR NOT NULL,
    delivery_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.EXECUTION_TERMS
    TO ROLE NORTHBRIDGE_DBT_DEV;

USE ROLE SYSADMIN;
DESCRIBE TABLE NORTHBRIDGE_DEV.RAW.EXECUTION_TERMS;
