-- Keep each execution message intact before dbt extracts its fields.
USE ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS (
    payload VARIANT NOT NULL,
    source_system VARCHAR NOT NULL,
    scenario_id VARCHAR NOT NULL,
    delivery_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_JSON
    TYPE = JSON;

CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS_STAGE
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.OMS_JSON;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.OMS_EVENTS
    TO ROLE NORTHBRIDGE_DBT_DEV;

USE ROLE SYSADMIN;
