-- Set up the RAW table and stage used by settlement ingestion.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS (
    payload VARIANT NOT NULL,
    delivery_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);
CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_JSON TYPE = JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_STAGE
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.SETTLEMENT_JSON;
USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS TO ROLE NORTHBRIDGE_DBT_DEV;
USE ROLE SYSADMIN;
