USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.REPLAY_INPUTS (
    payload VARIANT NOT NULL,
    delivery_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);
CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.REPLAY_JSON TYPE = JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.REPLAY_STAGE
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REPLAY_JSON;
USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.REPLAY_INPUTS TO ROLE NORTHBRIDGE_DBT_DEV;
USE ROLE SYSADMIN;

PUT 'file://C:/Users/UCHE/Desktop/Hedgefund-Finance-Pipeline-on-Snowflake/data/replays/sim-replay-406bbef8179cdbb0a3dd6df3/records.jsonl'
    @NORTHBRIDGE_DEV.RAW.REPLAY_STAGE/sim-replay-406bbef8179cdbb0a3dd6df3/
    AUTO_COMPRESS = TRUE OVERWRITE = FALSE;
COPY INTO NORTHBRIDGE_DEV.RAW.REPLAY_INPUTS
    (payload, delivery_id, source_file, source_row_number)
FROM (
    SELECT t.$1, 'sim-replay-406bbef8179cdbb0a3dd6df3', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
    FROM @NORTHBRIDGE_DEV.RAW.REPLAY_STAGE/sim-replay-406bbef8179cdbb0a3dd6df3/ t
)
FILES = ('records.jsonl.gz')
FILE_FORMAT = (FORMAT_NAME = 'NORTHBRIDGE_DEV.RAW.REPLAY_JSON')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

SELECT payload:record_type::varchar AS record_type, COUNT(*) AS records
FROM NORTHBRIDGE_DEV.RAW.REPLAY_INPUTS
WHERE delivery_id = 'sim-replay-406bbef8179cdbb0a3dd6df3'
GROUP BY record_type;
