-- Provision raw storage; reviews are audit history, not applied accounting rules.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS (
    payload VARIANT NOT NULL,
    snapshot_id VARCHAR NOT NULL,
    load_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38,0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTION_REVIEWS (
    payload VARIANT NOT NULL,
    snapshot_id VARCHAR NOT NULL,
    load_id VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38,0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);
CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS_JSON TYPE=JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS_STAGE
    FILE_FORMAT=NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS_JSON;
USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.CORPORATE_ACTIONS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.CORPORATE_ACTION_REVIEWS TO ROLE NORTHBRIDGE_DBT_DEV;
USE ROLE SYSADMIN;
