-- Append-only operational history for calculation runs and published NAV.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.PIPELINE_RUN_EVENTS (
    event_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    event_type VARCHAR NOT NULL,
    business_date DATE NOT NULL,
    occurred_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    replay_delivery_id VARCHAR NOT NULL,
    price_delivery_id VARCHAR NOT NULL,
    broker_delivery_id VARCHAR NOT NULL,
    code_version VARCHAR NOT NULL,
    details VARIANT NOT NULL,
    recorded_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.NAV_PUBLICATIONS (
    publication_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    scenario_id VARCHAR NOT NULL,
    business_date DATE NOT NULL,
    account_id VARCHAR NOT NULL,
    currency VARCHAR NOT NULL,
    published_nav NUMBER(38, 9) NOT NULL,
    calculation_basis VARCHAR NOT NULL,
    published_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    replay_delivery_id VARCHAR NOT NULL,
    price_delivery_id VARCHAR NOT NULL,
    broker_delivery_id VARCHAR NOT NULL,
    code_version VARCHAR NOT NULL,
    exception_review_note VARCHAR,
    recorded_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.NAV_RESTATEMENTS (
    restatement_id VARCHAR NOT NULL,
    original_publication_id VARCHAR NOT NULL,
    replacement_publication_id VARCHAR NOT NULL,
    business_date DATE NOT NULL,
    account_id VARCHAR NOT NULL,
    currency VARCHAR NOT NULL,
    original_nav NUMBER(38, 9) NOT NULL,
    revised_nav NUMBER(38, 9) NOT NULL,
    nav_difference NUMBER(38, 9) NOT NULL,
    reason VARCHAR NOT NULL,
    approved_by VARCHAR NOT NULL,
    recorded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    recorded_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.NAV_CANDIDATES AS
SELECT scenario_id, business_date, account_id, currency, simplified_nav, calculation_basis
FROM NORTHBRIDGE_DEV.DBT_DEV.FCT_DAILY_NAV;

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.BROKER_RECONCILIATION_SUMMARY AS
SELECT
    statement_date,
    COUNT_IF(book_status <> 'MATCHED') AS position_exceptions,
    COUNT_IF(timeliness_status = 'LATE') AS late_records
FROM NORTHBRIDGE_DEV.DBT_DEV.FCT_POSITION_RECONCILIATION
GROUP BY statement_date;

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.CURRENT_NAV_PUBLICATIONS AS
SELECT * EXCLUDE publication_rank
FROM (
    SELECT p.*,
        ROW_NUMBER() OVER (
            PARTITION BY business_date, account_id, currency
            ORDER BY published_at DESC, publication_id DESC
        ) AS publication_rank
    FROM NORTHBRIDGE_DEV.OPERATIONS.NAV_PUBLICATIONS p
)
WHERE publication_rank = 1;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS NORTHBRIDGE_NAV_PUBLISHER;
GRANT ROLE NORTHBRIDGE_NAV_PUBLISHER TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.OPERATIONS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.NAV_CANDIDATES TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.BROKER_RECONCILIATION_SUMMARY TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.CURRENT_NAV_PUBLICATIONS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.PIPELINE_RUN_EVENTS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.NAV_PUBLICATIONS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.NAV_RESTATEMENTS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
USE ROLE SYSADMIN;
