-- Run after the production-named dbt graph and operations views are verified.
USE ROLE SYSADMIN;

DROP VIEW IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.STG_REPLAY_INPUTS;

DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DAILY_POSITIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DAILY_VALUATION;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DAILY_OBLIGATIONS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DIVIDEND_ACCRUALS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DAILY_CASH;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.REPLAY_DAILY_NAV;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.BROKER_POSITION_RECONCILIATION;
