-- Raw landing objects for the four final source feeds.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.FX_RATES (
    payload VARIANT NOT NULL, delivery_id VARCHAR NOT NULL, source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL, loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.TREASURY_RATES LIKE NORTHBRIDGE_DEV.RAW.FX_RATES;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.FUND_ADMIN_EVENTS LIKE NORTHBRIDGE_DEV.RAW.FX_RATES;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.BANK_CASH_STATEMENTS LIKE NORTHBRIDGE_DEV.RAW.FX_RATES;

CREATE FILE FORMAT IF NOT EXISTS NORTHBRIDGE_DEV.RAW.REFERENCE_JSON TYPE = JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.FX_RATES_STAGE FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.TREASURY_RATES_STAGE FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.FUND_ADMIN_STAGE FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.BANK_CASH_STAGE FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.FX_RATES TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.TREASURY_RATES TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.FUND_ADMIN_EVENTS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.BANK_CASH_STATEMENTS TO ROLE NORTHBRIDGE_DBT_DEV;

GRANT USAGE ON FILE FORMAT NORTHBRIDGE_DEV.RAW.REFERENCE_JSON TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.FX_RATES_STAGE TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.TREASURY_RATES_STAGE TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.FUND_ADMIN_STAGE TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.BANK_CASH_STAGE TO ROLE NORTHBRIDGE_INGEST;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.FX_RATES TO ROLE NORTHBRIDGE_INGEST;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.TREASURY_RATES TO ROLE NORTHBRIDGE_INGEST;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.FUND_ADMIN_EVENTS TO ROLE NORTHBRIDGE_INGEST;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.BANK_CASH_STATEMENTS TO ROLE NORTHBRIDGE_INGEST;
USE ROLE SYSADMIN;
