-- Cost controls for the current small, sequential development workload.
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS NORTHBRIDGE_DEV_MONITOR
    WITH CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE COMPUTE_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE
    RESOURCE_MONITOR = NORTHBRIDGE_DEV_MONITOR;

SHOW WAREHOUSES LIKE 'COMPUTE_WH';
SHOW RESOURCE MONITORS LIKE 'NORTHBRIDGE_DEV_MONITOR';
