-- Run control is append-only: retries add events instead of replacing history.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.RUNS (
    run_id VARCHAR NOT NULL,
    run_mode VARCHAR NOT NULL,
    business_date DATE NOT NULL,
    calculation_cutoff TIMESTAMP_TZ NOT NULL,
    scenario_id VARCHAR,
    code_version VARCHAR NOT NULL,
    created_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    created_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.RUN_INPUTS (
    run_id VARCHAR NOT NULL,
    source_name VARCHAR NOT NULL,
    delivery_id VARCHAR NOT NULL,
    manifest_sha256 VARCHAR NOT NULL,
    expected_rows NUMBER(38, 0) NOT NULL,
    recorded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    recorded_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.RUN_EVENTS (
    event_id VARCHAR NOT NULL,
    run_id VARCHAR NOT NULL,
    attempt_number NUMBER(38, 0) NOT NULL,
    step_name VARCHAR NOT NULL,
    event_type VARCHAR NOT NULL,
    occurred_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    details VARIANT NOT NULL,
    recorded_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.CURRENT_RUN_STATUS AS
WITH pipeline_events AS (
    SELECT
        run_id,
        attempt_number,
        event_type,
        occurred_at,
        ROW_NUMBER() OVER (
            PARTITION BY run_id
            ORDER BY occurred_at DESC, event_id DESC
        ) AS event_rank
    FROM NORTHBRIDGE_DEV.OPERATIONS.RUN_EVENTS
    WHERE step_name = 'pipeline'
)
SELECT
    r.run_id,
    r.run_mode,
    r.business_date,
    r.calculation_cutoff,
    r.scenario_id,
    r.code_version,
    COALESCE(e.attempt_number, 0) AS latest_attempt,
    COALESCE(e.event_type, 'REGISTERED') AS current_status,
    e.occurred_at AS status_changed_at,
    r.created_at,
    r.created_by
FROM NORTHBRIDGE_DEV.OPERATIONS.RUNS r
LEFT JOIN pipeline_events e
    ON r.run_id = e.run_id
   AND e.event_rank = 1;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS NORTHBRIDGE_RUNNER;
GRANT ROLE NORTHBRIDGE_RUNNER TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NORTHBRIDGE_RUNNER;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_RUNNER;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.OPERATIONS TO ROLE NORTHBRIDGE_RUNNER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.RUNS TO ROLE NORTHBRIDGE_RUNNER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.RUN_INPUTS TO ROLE NORTHBRIDGE_RUNNER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.RUN_EVENTS TO ROLE NORTHBRIDGE_RUNNER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.CURRENT_RUN_STATUS TO ROLE NORTHBRIDGE_RUNNER;

USE ROLE SYSADMIN;
SELECT table_name
FROM NORTHBRIDGE_DEV.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'OPERATIONS'
  AND table_name IN ('RUNS', 'RUN_INPUTS', 'RUN_EVENTS', 'CURRENT_RUN_STATUS')
ORDER BY table_name;
