-- Snowpipe loads validated OMS files from the existing internal stage.
USE ROLE SYSADMIN;

CREATE PIPE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.OMS_EVENTS_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO NORTHBRIDGE_DEV.RAW.OMS_EVENTS (
    payload,
    source_system,
    scenario_id,
    delivery_id,
    source_file,
    source_row_number
)
FROM (
    SELECT
        t.$1,
        t.$1:source_system::VARCHAR,
        t.$1:scenario_id::VARCHAR,
        SPLIT_PART(METADATA$FILENAME, '/', -2),
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @NORTHBRIDGE_DEV.RAW.OMS_EVENTS_STAGE t
)
FILE_FORMAT = (FORMAT_NAME = 'NORTHBRIDGE_DEV.RAW.OMS_JSON');

USE ROLE SECURITYADMIN;
GRANT MONITOR, OPERATE ON PIPE NORTHBRIDGE_DEV.RAW.OMS_EVENTS_PIPE
    TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.OMS_EVENTS_STAGE
    TO ROLE NORTHBRIDGE_INGEST;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.OMS_EVENTS
    TO ROLE NORTHBRIDGE_INGEST;
GRANT USAGE ON FILE FORMAT NORTHBRIDGE_DEV.RAW.OMS_JSON
    TO ROLE NORTHBRIDGE_INGEST;

USE ROLE SYSADMIN;
DESCRIBE PIPE NORTHBRIDGE_DEV.RAW.OMS_EVENTS_PIPE;
