-- Read-only inventory before changing the role hierarchy or schema ownership.
USE ROLE SECURITYADMIN;

SHOW ROLES LIKE 'NORTHBRIDGE%';
SHOW USERS LIKE 'NORTHBRIDGE%';

SHOW GRANTS TO ROLE NORTHBRIDGE_INGEST;
SHOW GRANTS TO ROLE NORTHBRIDGE_DBT_DEV;
SHOW GRANTS TO ROLE NORTHBRIDGE_RUNNER;
SHOW GRANTS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;

USE ROLE SYSADMIN;

SELECT
    schema_name,
    schema_owner,
    is_managed_access
FROM NORTHBRIDGE_DEV.INFORMATION_SCHEMA.SCHEMATA
WHERE schema_name NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
ORDER BY schema_name;

SELECT
    table_schema,
    table_name,
    table_type,
    table_owner,
    retention_time
FROM NORTHBRIDGE_DEV.INFORMATION_SCHEMA.TABLES
WHERE table_schema NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
ORDER BY table_schema, table_name;

SHOW PIPES IN DATABASE NORTHBRIDGE_DEV;
SHOW TASKS IN DATABASE NORTHBRIDGE_DEV;
