-- Run only after the dedicated publisher key has connected successfully.
USE ROLE SECURITYADMIN;

REVOKE ROLE NORTHBRIDGE_NAV_PUBLISHER FROM USER NORTHBRIDGE_DBT_LOCAL;
ALTER USER NORTHBRIDGE_DBT_LOCAL SET DEFAULT_SECONDARY_ROLES = ();

SHOW GRANTS TO USER NORTHBRIDGE_DBT_LOCAL;
SHOW GRANTS TO USER NORTHBRIDGE_NAV_PUBLISHER_LOCAL;
