-- One receipt per immutable source delivery. A daily run may start only when
-- every pinned delivery is present and its Snowflake row count matches its manifest.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES (
    source_name VARCHAR NOT NULL,
    delivery_id VARCHAR NOT NULL,
    manifest_sha256 VARCHAR NOT NULL,
    expected_rows NUMBER(38, 0) NOT NULL,
    received_rows NUMBER(38, 0) NOT NULL,
    delivery_status VARCHAR NOT NULL,
    first_loaded_at TIMESTAMP_LTZ,
    last_loaded_at TIMESTAMP_LTZ,
    registered_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    registered_by VARCHAR DEFAULT CURRENT_USER() NOT NULL
);

-- Receipts are inserted by each source loader after checking its manifest and row count.

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.DELIVERY_EXCEPTIONS AS
SELECT *
FROM NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES
WHERE delivery_status <> 'READY' OR received_rows <> expected_rows;

USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.OPERATIONS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.DELIVERY_EXCEPTIONS TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.OPERATIONS TO ROLE NORTHBRIDGE_INGEST;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES TO ROLE NORTHBRIDGE_INGEST;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES TO ROLE NORTHBRIDGE_RUNNER;

USE ROLE SYSADMIN;
SELECT source_name, delivery_id, expected_rows, received_rows, delivery_status
FROM NORTHBRIDGE_DEV.OPERATIONS.DELIVERIES
ORDER BY source_name;
