-- Human review sits between a successful calculation and NAV publication.
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.OPERATIONS.NAV_APPROVALS (
    approval_id VARCHAR NOT NULL,
    business_date DATE NOT NULL,
    scenario_id VARCHAR NOT NULL,
    candidate_hash VARCHAR NOT NULL,
    decision VARCHAR NOT NULL,
    review_note VARCHAR NOT NULL,
    reviewed_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    reviewed_by VARCHAR DEFAULT CURRENT_USER() NOT NULL,
    reviewer_role VARCHAR DEFAULT CURRENT_ROLE() NOT NULL
);

ALTER TABLE NORTHBRIDGE_DEV.OPERATIONS.NAV_PUBLICATIONS
    ADD COLUMN IF NOT EXISTS approval_id VARCHAR;

CREATE OR REPLACE VIEW NORTHBRIDGE_DEV.OPERATIONS.NAV_REVIEW_CANDIDATES AS
SELECT
    scenario_id,
    business_date,
    COUNT(*) AS nav_rows,
    SHA2(
        LISTAGG(
            CONCAT_WS('|', account_id, currency, TO_VARCHAR(simplified_nav), calculation_basis),
            '||'
        ) WITHIN GROUP (ORDER BY account_id, currency),
        256
    ) AS candidate_hash,
    SUM(simplified_nav) AS total_nav,
    MIN(calculation_basis) AS calculation_basis
FROM NORTHBRIDGE_DEV.OPERATIONS.NAV_CANDIDATES
GROUP BY scenario_id, business_date;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS NORTHBRIDGE_NAV_REVIEWER;
GRANT ROLE NORTHBRIDGE_NAV_REVIEWER TO ROLE SYSADMIN;
GRANT ROLE NORTHBRIDGE_NAV_REVIEWER TO USER CHIGGZY;
GRANT USAGE ON DATABASE NORTHBRIDGE_DEV TO ROLE NORTHBRIDGE_NAV_REVIEWER;
GRANT USAGE ON SCHEMA NORTHBRIDGE_DEV.OPERATIONS TO ROLE NORTHBRIDGE_NAV_REVIEWER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.NAV_REVIEW_CANDIDATES TO ROLE NORTHBRIDGE_NAV_REVIEWER;
GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.BROKER_RECONCILIATION_SUMMARY TO ROLE NORTHBRIDGE_NAV_REVIEWER;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.NAV_APPROVALS TO ROLE NORTHBRIDGE_NAV_REVIEWER;

GRANT SELECT ON VIEW NORTHBRIDGE_DEV.OPERATIONS.NAV_REVIEW_CANDIDATES TO ROLE NORTHBRIDGE_NAV_PUBLISHER;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.OPERATIONS.NAV_APPROVALS TO ROLE NORTHBRIDGE_NAV_PUBLISHER;

USE ROLE SYSADMIN;
SELECT * FROM NORTHBRIDGE_DEV.OPERATIONS.NAV_REVIEW_CANDIDATES
ORDER BY business_date DESC, scenario_id;
