-- One-time migration for the first SYSADMIN-owned task draft.
-- ACCOUNTADMIN is needed only for Snowflake's global EXECUTE TASK privilege.
USE ROLE SYSADMIN;
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.DAILY_CLOSE_AUDIT SUSPEND;
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.DAILY_CLOSE SUSPEND;

USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA NORTHBRIDGE_DEV.OPERATIONS
    TO ROLE NORTHBRIDGE_DBT_DEV COPY CURRENT GRANTS;

USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE NORTHBRIDGE_DBT_DEV;

USE ROLE NORTHBRIDGE_DBT_DEV;
SHOW TASKS IN SCHEMA NORTHBRIDGE_DEV.OPERATIONS;
