-- One-time Snowflake setup for pull-request builds from GitHub Actions.
-- Re-running this file keeps the same role, user, warehouse and CI base.

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS NORTHBRIDGE_DBT_CI
    COMMENT = 'Builds and tests pull-request dbt code in disposable database clones';

CREATE USER IF NOT EXISTS NORTHBRIDGE_GITHUB_CI
    TYPE = SERVICE
    DEFAULT_ROLE = NORTHBRIDGE_DBT_CI
    DEFAULT_WAREHOUSE = NORTHBRIDGE_CI_WH
    WORKLOAD_IDENTITY = (
        TYPE = OIDC
        ISSUER = 'https://token.actions.githubusercontent.com'
        SUBJECT = 'repo:Uche-anya@108993926/Hedgefund-Finance-Platform-on-Snowflake@1379734472:environment:ci'
    )
    COMMENT = 'GitHub Actions identity for Northbridge pull-request checks';

ALTER USER NORTHBRIDGE_GITHUB_CI SET
    TYPE = SERVICE
    DEFAULT_ROLE = NORTHBRIDGE_DBT_CI
    DEFAULT_WAREHOUSE = NORTHBRIDGE_CI_WH
    WORKLOAD_IDENTITY = (
        TYPE = OIDC
        ISSUER = 'https://token.actions.githubusercontent.com'
        SUBJECT = 'repo:Uche-anya@108993926/Hedgefund-Finance-Platform-on-Snowflake@1379734472:environment:ci'
    );

GRANT ROLE NORTHBRIDGE_DBT_CI TO USER NORTHBRIDGE_GITHUB_CI;
GRANT ROLE NORTHBRIDGE_DBT_CI TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NORTHBRIDGE_CI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Small warehouse for pull-request dbt builds';

-- This is a reviewed snapshot. Pull requests clone it and never write here.
CREATE DATABASE IF NOT EXISTS NORTHBRIDGE_CI_BASE
    CLONE NORTHBRIDGE_DEV;

COMMENT ON DATABASE NORTHBRIDGE_CI_BASE IS
    'Reviewed source snapshot used to create pull-request databases';

CREATE SCHEMA IF NOT EXISTS NORTHBRIDGE_CI_BASE.DBT_CI
    COMMENT = 'Destination schema inherited by pull-request database clones';

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE NORTHBRIDGE_CI_WH TO ROLE NORTHBRIDGE_DBT_CI;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE NORTHBRIDGE_DBT_CI;

USE ROLE SECURITYADMIN;
-- USAGE on the base is required to clone it. CI receives no write privilege on it.
GRANT USAGE ON DATABASE NORTHBRIDGE_CI_BASE TO ROLE NORTHBRIDGE_DBT_CI;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NORTHBRIDGE_CI_BASE TO ROLE NORTHBRIDGE_DBT_CI;
GRANT SELECT ON ALL TABLES IN DATABASE NORTHBRIDGE_CI_BASE TO ROLE NORTHBRIDGE_DBT_CI;
GRANT SELECT ON ALL VIEWS IN DATABASE NORTHBRIDGE_CI_BASE TO ROLE NORTHBRIDGE_DBT_CI;

-- Child-object grants are inherited by each database clone.
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NORTHBRIDGE_CI_BASE.DBT_CI
    TO ROLE NORTHBRIDGE_DBT_CI;
GRANT CREATE DBT PROJECT ON SCHEMA NORTHBRIDGE_CI_BASE.OPERATIONS
    TO ROLE NORTHBRIDGE_DBT_CI;

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS NORTHBRIDGE_CI_MONITOR
    WITH CREDIT_QUOTA = 2
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE NORTHBRIDGE_CI_WH SET
    RESOURCE_MONITOR = NORTHBRIDGE_CI_MONITOR;

-- Prove the CI role can clone, read raw data, write dbt relations and clean up.
USE ROLE NORTHBRIDGE_DBT_CI;

CREATE OR REPLACE TRANSIENT DATABASE NORTHBRIDGE_CI_PERMISSION_CHECK
    CLONE NORTHBRIDGE_CI_BASE;

CREATE VIEW NORTHBRIDGE_CI_PERMISSION_CHECK.DBT_CI.CI_PERMISSION_CHECK AS
SELECT COUNT(*) AS historical_price_rows
FROM NORTHBRIDGE_CI_PERMISSION_CHECK.RAW.HISTORICAL_PRICES;

SELECT *
FROM NORTHBRIDGE_CI_PERMISSION_CHECK.DBT_CI.CI_PERMISSION_CHECK;

DROP DATABASE NORTHBRIDGE_CI_PERMISSION_CHECK;

USE ROLE SECURITYADMIN;
SHOW GRANTS TO ROLE NORTHBRIDGE_DBT_CI;
SHOW USER WORKLOAD IDENTITY AUTHENTICATION METHODS FOR USER NORTHBRIDGE_GITHUB_CI;

USE ROLE SYSADMIN;
SHOW WAREHOUSES LIKE 'NORTHBRIDGE_CI_WH';
SHOW DATABASES LIKE 'NORTHBRIDGE_CI_BASE';
