-- A second feed: settlement confirmations arrive separately from OMS fills.
USE ROLE SYSADMIN;

CREATE PIPE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS (
    payload, delivery_id, source_file, source_row_number
)
FROM (
    SELECT t.$1,
           SPLIT_PART(METADATA$FILENAME, '/', -2),
           METADATA$FILENAME,
           METADATA$FILE_ROW_NUMBER
    FROM @NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_STAGE t
)
FILE_FORMAT = (FORMAT_NAME = 'NORTHBRIDGE_DEV.RAW.SETTLEMENT_JSON');

USE ROLE SECURITYADMIN;
GRANT MONITOR, OPERATE ON PIPE NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_PIPE
    TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_STAGE
    TO ROLE NORTHBRIDGE_INGEST;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS
    TO ROLE NORTHBRIDGE_INGEST;
GRANT USAGE ON FILE FORMAT NORTHBRIDGE_DEV.RAW.SETTLEMENT_JSON
    TO ROLE NORTHBRIDGE_INGEST;

USE ROLE SYSADMIN;
DESCRIBE PIPE NORTHBRIDGE_DEV.RAW.SETTLEMENT_EVENTS_PIPE;
