-- Custodian cash confirmations for dividend entitlements.
USE ROLE SYSADMIN;
CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_EVENTS
    LIKE NORTHBRIDGE_DEV.RAW.FX_RATES;
CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_STAGE
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_EVENTS
    TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_EVENTS
    TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.DIVIDEND_PAYMENT_STAGE
    TO ROLE NORTHBRIDGE_INGEST;
