-- Landing table for versioned close extracts produced by the Python close.
-- These are provisional analysis inputs, not a published NAV ledger.
USE ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING (
    record_type VARCHAR NOT NULL,
    payload VARIANT NOT NULL,
    ledger_id VARCHAR NOT NULL,
    manifest_sha256 VARCHAR NOT NULL,
    source_file VARCHAR NOT NULL,
    source_row_number NUMBER(38, 0) NOT NULL,
    loaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

CREATE STAGE IF NOT EXISTS NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING_STAGE
    FILE_FORMAT = NORTHBRIDGE_DEV.RAW.REFERENCE_JSON;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING
    TO ROLE NORTHBRIDGE_DBT_DEV;
GRANT INSERT, SELECT ON TABLE NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING
    TO ROLE NORTHBRIDGE_INGEST;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.TWO_YEAR_REPORTING_STAGE
    TO ROLE NORTHBRIDGE_INGEST;
