-- Let the ingestion service load checked daily market files.
USE ROLE SECURITYADMIN;
GRANT READ, WRITE ON STAGE NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES_STAGE
    TO ROLE NORTHBRIDGE_INGEST;
GRANT USAGE ON FILE FORMAT NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES_CSV
    TO ROLE NORTHBRIDGE_INGEST;
GRANT SELECT, INSERT ON TABLE NORTHBRIDGE_DEV.RAW.HISTORICAL_PRICES
    TO ROLE NORTHBRIDGE_INGEST;
