-- Manual pilot for one pinned candidate. The root has no schedule.
USE ROLE SYSADMIN;

-- Re-running this file safely replaces the same manual pilot graph.
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_FINALIZER SUSPEND;
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_CAPTURE SUSPEND;
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT SUSPEND;
ALTER TASK IF EXISTS NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE SUSPEND;

CREATE OR REPLACE TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE
    WAREHOUSE = COMPUTE_WH
    OVERLAP_POLICY = NO_OVERLAP
    CONFIG = $${"request_id": "", "supersedes_request_id": ""}$$
AS
    CALL NORTHBRIDGE_DEV.OPERATIONS.START_CLOSE_PILOT();

CREATE OR REPLACE TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT
    WAREHOUSE = COMPUTE_WH
    AFTER NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE
AS
    CALL NORTHBRIDGE_DEV.OPERATIONS.RUN_CLOSE_DBT();

CREATE OR REPLACE TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_CAPTURE
    WAREHOUSE = COMPUTE_WH
    AFTER NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT
AS
    CALL NORTHBRIDGE_DEV.OPERATIONS.CAPTURE_CLOSE_PILOT();

CREATE OR REPLACE TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_FINALIZER
    WAREHOUSE = COMPUTE_WH
    FINALIZE = NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE
AS
    CALL NORTHBRIDGE_DEV.OPERATIONS.FINISH_CLOSE_PILOT();

-- A manual run of a suspended root triggers only resumed children.
-- The root has no schedule, so this graph cannot run by itself.
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT RESUME;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_CAPTURE RESUME;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_FINALIZER RESUME;

SHOW TASKS IN SCHEMA NORTHBRIDGE_DEV.OPERATIONS;
