-- DEV-only failure drill. Restore 65_close_pilot_tasks.sql after this run ends.
USE ROLE SYSADMIN;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE SUSPEND;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT SUSPEND;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT MODIFY AS SELECT 1 / 0;
ALTER TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_DBT RESUME;
EXECUTE TASK NORTHBRIDGE_DEV.OPERATIONS.CLOSE_PILOT_GATE;
