-- Run after the renamed dbt build and close Task both pass in DEV.
-- These derived tables and the old seed copy can be rebuilt from source.
USE ROLE SYSADMIN;

DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_ACCOUNT_DAY;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_POSITION_DAY;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_POSITIONS_FROM_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_CASH_FROM_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_DIVIDEND_BALANCES;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.FCT_TWO_YEAR_NAV_FROM_EVENTS;
DROP TABLE IF EXISTS NORTHBRIDGE_DEV.DBT_DEV.TWO_YEAR_ACTION_DECISIONS;
